version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://slbasha5555:0dtBv6tvnVrRRQGY@cluster0.ozxk2.mongodb.net/search_project

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
