version: '3.8'
services:
  backend:
    build: ./backend
    environment:
      - MONGO_URI=mongodb+srv://slbasha5555:0dtBv6tvnVrRRQGY@cluster0.ozxk2.mongodb.net/search_project
      - REDIS_URL=redis://redis:6379
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
    networks:
      - app-network

  frontend:
    build: ./frontend
    networks:
      - app-network

  redis:
    image: redis:alpine
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
